name: Build for Acceptance
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy-to-acceptance:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      - run: yarn install
      - name: EAS build and deploy
        run: eas build --platform all --profile acceptance --non-interactive
